## Notebook para aprender sobre Numpy

Numpy es un programa desarrollado sobre python para atender ciertas necesidades de velocidad de computación. Numpy es más eficiente que python en acciones con repeticiones o loops mayores a 5. 

Numpy arrays Importante 

# Numpy ufuncs 

Universal Functions. They operate elemnt-wise on arrays. Osea las unfuncs operan el array como un elemento unico. 

In [3]:
import numpy as np

In [10]:
a = [1, 2, 3]
a = np.array(a)

La forma de ver el funcionamiento de Numpy es a través de las python lists. Python analiza cada uno de los elementos de la lista, "entiende" el tipo de elemento (string, integer, etc) y luego hace la operación. Aparentemente esta función hace a python lento en comparación con Numpy. Cuando las listas se vuelven muy grandes y Python debe repetir el proceso una y otra vez, deja de ser eficiente. 

In [ ]:
# Dynamic typing.
def multiply_elementwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

multiply_elementwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

In [6]:
[type(x) for x in _]

[int, complex, float, str]

Si vez en el ejemplo superior, Python es capaz de realizar operaciones con distintos tipos de inputs. 

Python is an interpretitative language 

In [8]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


Dispatch *once per operation (or array)* instead of *once per element*.

numpy is a python module. Lo importante son los arrays 

In [4]:
import numpy as np

data = np.array([1.0, 2, 3, 4, 5, 6, 7, 8])

print("Data:", data)
print("===========")
print("DType:", data.dtype)
print("Shape:", data.shape)

Data: [1. 2. 3. 4. 5. 6. 7. 8.]
DType: float64
Shape: (8,)


Importante notar como cambia el DType y Shape cuando modificas el array. Al momento de escribir un float, toda la lista cambia a floats. 

In [65]:
import numpy as np

data = np.array([1., 2, 3, 4, 5, 6, 7, 8]).reshape(2, 4) #(2, 2, 2)

print("Data:", data)
print("===========")
print("DType:", data.dtype)
print("Shape:", data.shape)

Data: [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
DType: float64
Shape: (2, 4)


In [66]:
# Numpy provides operators that "vectorize" over the entire array.
data + data #puede ser cualquier ufunct 

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.]])

In [17]:
# ejemplo, digamos que el array es un csv con returns as %, 
# we could actually just divide the array by 100 to get decimal places.
# Check the edhec toolbox. I think thats what they do in get_returns functions. 

In [67]:
data/100

array([[0.01, 0.02, 0.03, 0.04],
       [0.05, 0.06, 0.07, 0.08]])

In [31]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: could not convert string to float: 'foo'

In [58]:
#data[1] = "10"

In [59]:
data

array([[ 1.,  2.,  3.,  4.],
       [10., 10., 10., 10.]])

In [ ]:
# We also can't grow an array once it's created.
data.append(3)

In [ ]:

# We **can** reshape an array as long as the number of elements doesn't change.
reshaped = data.reshape(4, 2)
reshaped

Numpy Toolbox - Overview

Numpy can be fast because it allows us to specify operations to perform against an entire array.

We can break down the tools provided by numpy into a few categories:

Array Creation and Reshaping
Universal Functions (UFuncs)
Selection
Reductions
Broadcasting
Taken together, these operations form an expressive toolbox that can solve a diverse set of problems.

### Creating Arrays 

- np.array: Construct an array from a list of Python objects. Básicamente transformas la lista a una lista en formato Numpy


- np.arange: Numpy equivalent of the range function.

- np.linspace: Create an array from evenly-spaced points between two values. #(-1, 1, 10) del -1 al 1 crear 10 evenly spaced numbers. Como pywidgets básicamente.

- np.random: Randomly-generated values from various distributions. 
Lista de distribuciones: https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html

- np.full/np.ones/np.zeros: Create an array of a given shape with a constant value.

In [72]:
np.random.normal(0,1,100) #0 mean, 1 variance, n=100

array([ 0.91418631, -1.10401107, -0.80312192, -0.47887516, -0.92381192,
       -0.13140108,  0.43992898, -1.83052234, -0.26706745, -0.48110905,
       -1.38440958,  2.19083649, -1.21655844,  0.30453878,  0.79857542,
       -0.40835349,  0.7249303 , -0.82129364, -0.12031923,  0.49008458,
        1.14288372, -1.40208954, -0.52185808, -0.28248635, -1.26228716,
        0.45936973, -0.74652634,  0.51790913, -0.52748082,  0.90794834,
       -0.03416013, -0.20716401, -1.03409775, -1.82838021, -1.83828941,
       -0.50107933, -0.45790223,  1.26058236,  0.63174495, -1.0564009 ,
       -1.96386006,  1.3944027 ,  0.39294977,  1.9842911 , -0.77433837,
        0.00466831,  0.85876742,  0.66763274, -0.2693499 , -0.86808785,
        0.29185195,  0.89401846, -0.46279277, -1.85559227, -0.24813897,
        0.20606076,  1.08629253,  1.49317376, -0.71364581, -0.04496594,
        1.09360974,  2.52291851, -0.06996713,  0.66192223, -0.21197736,
       -0.7658668 ,  0.20219923, -1.63953106,  0.07514277,  0.18

### Creating Arrays continued

- np.eye/np.identity/np.diag: Arrays with values on the diagonal. Useful for linear algebra.
- np.load/np.save: Load and save values from disk.
- pandas.read_csv: Read values from a CSV. Returns a pandas.DataFrame.

**Lo normal es crear arrays a través de pandas.** 

Reshaping arrays = Once we've created an array, the next step is often to reshape the array to have the dimensions we want.

In [83]:
data = np.arange(16)
data.reshape(4, 4) #the product of the combination must add up to the number of elements
#(2, 2, 2, 2)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Transpose = A particularly common way to reshape arrays is to swap a pair of dimensions.

In [85]:
data = np.arange(12).reshape(3, 4)
print("data:\n", data)
print("data.T:\n", data.T)

data:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
data.T:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Date cuenta que cuando creas un rango, recibis el equivalente a una lista o un vector de una dimensión. Reshape modifica la lista y la formatea en una tabla? y transpose la adapta al formato que queres, osea podes transpose tabla b para que sea operable con tabla a por ejemplo. 

In [101]:
np.arange(1, 7).reshape(2,3).T #T in this case creates the shape (3,2)

array([[1, 4],
       [2, 5],
       [3, 6]])

## Ufuncts 

Universal functions (ufuncs) are functions that can be applied across one or more arrays of the same shape.

They come in two main varieties:

Unary UFuncs apply a 1-argument function to every element of an array.

Binary UFuncs apply a 2-argument function to corresponding elements from two arrays.

In [102]:
data = np.arange(1, 16).reshape(3, 5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [107]:
# Unary functions.
np.sqrt(data)
#np.log(data)
#np.sin(data)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [108]:
# Comparison operations
(data % 3) == 0

array([[False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [109]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False,  True, False, False, False]])

In [110]:
# | <- or operator, found in your keyboard english version  

In [111]:
# @ is a matrix multiplication symbol

In [114]:
data @ data.T

array([[ 55, 130, 205],
       [130, 330, 530],
       [205, 530, 855]])

All binary operator ufuncs have a normal function version:

- +,-,*,/ are the same as add, subtract, multiply, divide
- &, |, ^, ~ are the same as bitwise_and, bitwise_or, bitwise_xor, bitwise_not

Binary ufuncs are equipped with methods that implement common algorithms in terms of the ufunc.

- reduce computes a summary by inserting the binary operator between each element.
- accumulate is like reduce, but it outputs the intermediate values.
- outer computes the binary operator on every pair of elements from two arrays.

In [123]:
data = (np.random.RandomState(1).randint(-10, 10, 18).reshape(3, 6))
data

array([[ -5,   1,   2,  -2,  -1,   1],
       [ -5,   5, -10,   6,  -9,   2],
       [ -3,   3,  -4,   8,  -5,   8]])

In [127]:
np.add.accumulate(data, axis=0)

array([[ -5,   1,   2,  -2,  -1,   1],
       [-10,   6,  -8,   4, -10,   3],
       [-13,   9, -12,  12, -15,  11]])

In [129]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [136]:
sines.reshape(5, 2)[0, 1] #[]indexing. revisar las formas de indexing en python lists

0.34185384854620343

In [137]:
sines[:3]

array([0.        , 0.34185385, 0.64251645])

In [138]:
sines[::3]

array([0.        , 0.86575984, 0.8665558 , 0.00159265])

In [142]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("\nsines > 0.5:\n", sines > 0.5)
print("\nsines[sines > 0.5]:\n", sines[sines > 0.5]) #Here you get the values 
# where the condition sines > 0.5 is true IMPORTANTE. Esta es una forma de crear 
# percentiles for factors i.e. filter dataframes 

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]

sines > 0.5:
 [False False  True  True  True  True  True  True False False]

sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [143]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [144]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [145]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [146]:
prices = np.array([12, 6, 10, 5, 6])
tickers = np.array(['A', 'B', 'C', 'D', 'E'])

In [147]:
# Sort assets by price by using the permutation that would sort market caps on ``assets``.
sorter = np.argsort(prices)
tickers[sorter]


array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

On multi-dimensional arrays, we can slice along each axis independently.

In [187]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [188]:
#data[1]             # Get the second row.
data[:, 0]             # Get the second column.
#data[:2, :2]       # Get the first two rows and first two columns.
#data[:2, [0, -1]]  # Get the first two rows, first/last columns.

array([ 0,  5, 10, 15, 20])

# Reductions 

Another common class of operations in numpy is to "summarize" our data along a particular axis.

Examples of common "summaries" are:

- Minimum/Maximum
- Location of Minimum/Maximum (argmin/argmax)
- Sum/Product
- Statistical Moments (mean, variance, skew, kurtosis)

In [161]:
def variance(x): #remember that x can be (is) an array
    return ((x - x.mean()) ** 2).sum() / len(x)

In [162]:
xs = np.random.standard_normal(1000)
variance(xs)

0.9847483225762537

In [163]:
np.var(xs)

0.9847483225762537

In [164]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [168]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [166]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

## There are two axes, 0 and 1 for a two dimensional space. (just google numpy axis)

In Numpy dimensions are called axes. The number of axes is rank. For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3

In [171]:
data.sum(axis=0) #sums columns

array([30, 33, 36, 39, 42, 45, 48, 51, 54, 57])

In [172]:
data.sum(axis=1) #sums rows

array([ 45, 145, 245])

## Axis 0 is for columns 

## Axis 1 is for rows 

In [184]:
data.min(axis=1)

array([ 0, 10, 20])

In [182]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [193]:
np.array([2], [3], [3],
           [4], [5], [6])

ValueError: only 2 non-keyword arguments accepted

In [195]:
np.array([2], [3], [3])

ValueError: only 2 non-keyword arguments accepted

# Ejemplo

asdfasdfasdfasdfds

In [1]:
x = 1
y = 2

In [2]:
x + y

3